##ilçe seviyesindeki excel dosyalarının içerik sayısına göre ilcelerin disturbution sayıları hesaplanmıstır.
import csv

with open('Ankarailce.csv', 'w', newline = '') as file:
    writer = csv.writer(file)
    writer.writerow(["name", "Supermarkets"])
    writer.writerow(["Akyurt", "60"])
    writer.writerow(["Altindag", "60"])
    writer.writerow(["Ayas", "30"])
    writer.writerow(["Bala", "20"])
    writer.writerow(["Beypazari", "50"])
    writer.writerow(["Camlidere", "9"])
    writer.writerow(["Cankaya", "60"])
    writer.writerow(["Cubuk", "60"])
    writer.writerow(["Elmadag", "37"])
    writer.writerow(["Etimesgut", "60"])
    writer.writerow(["Evren", "4"])
    writer.writerow(["Golbasi", "24"])
    writer.writerow(["Gudul", "10"])
    writer.writerow(["Haymana", "31"])
    writer.writerow(["Kalecik", "16"])
    writer.writerow(["Kazan", "60"])
    writer.writerow(["Kecioren", "60"])
    writer.writerow(["Kizilcahamam", "24"])
    writer.writerow(["Mamak", "60"])
    writer.writerow(["Nallihan", "31"])
    writer.writerow(["Polatli", "60"])
    writer.writerow(["Pursaklar", "60"])
    writer.writerow(["Sereflikochisar", "20"])
    writer.writerow(["Sincan", "60"])
    writer.writerow(["Yenimahalle", "60"])
file.close()    